abstract: ~
author: 'Victor Hsieh, C<< <victor at cpan.org> >>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: Module::Install version 0.62
license: perl
name: Baseball-Sabermetrics
no_index:
  directory:
    - examples
    - inc
    - t
recommends:
  WWW::Mechanize: 0.01
version: 0.01
